/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Escritorio;
import static Escritorio.Database.getConectar;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Diego
 */
public class Nuevo_user extends javax.swing.JFrame {
    private Connection conexion;     
    private Statement st;     
    private ResultSet rs;


    public Nuevo_user() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jp_nuevo_user = new javax.swing.JPanel();
        jl_usuario = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jl_pass = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jl_tipo = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        jl_rfc = new javax.swing.JLabel();
        jtf_rfc = new javax.swing.JTextField();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jl_confirm_pass = new javax.swing.JLabel();
        jp_pass = new javax.swing.JPasswordField();
        jp_pass_con = new javax.swing.JPasswordField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Usuario");

        jl_usuario.setText("Usuario:");

        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });

        jl_pass.setText("Contraseña:");

        jl_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_titulo.setText("Nuevo Usuario");

        jl_tipo.setText("Tipo:");

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", " " }));

        jl_rfc.setText("RFC");

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jl_confirm_pass.setText("Confirmar contraseña:");

        javax.swing.GroupLayout jp_nuevo_userLayout = new javax.swing.GroupLayout(jp_nuevo_user);
        jp_nuevo_user.setLayout(jp_nuevo_userLayout);
        jp_nuevo_userLayout.setHorizontalGroup(
            jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                                        .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jl_usuario)
                                            .addComponent(jtf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(jl_confirm_pass)
                                            .addComponent(jl_rfc)
                                            .addComponent(jp_pass_con))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_nuevo_userLayout.createSequentialGroup()
                                        .addComponent(jb_guardar)
                                        .addGap(24, 24, 24)))
                                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_pass)
                                    .addComponent(jl_tipo)
                                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jb_cancelar)))))
                    .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jl_titulo)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jp_nuevo_userLayout.setVerticalGroup(
            jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jl_titulo)
                .addGap(18, 18, 18)
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_usuario)
                    .addComponent(jl_pass))
                .addGap(1, 1, 1)
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_nuevo_userLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jp_pass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_confirm_pass)
                    .addComponent(jl_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_pass_con, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_rfc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_nuevo_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_guardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_nuevo_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_nuevo_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        SqlUsuario modsql = new SqlUsuario();
        usuario mod = new usuario();
        
        String pass = new String(jp_pass.getPassword());
        String passCon = new String(jp_pass_con.getPassword());
        
        if(pass.equals(passCon))
        {
            if(modsql.existeUsuario(jtf_usuario.getText())==0)
            {
            String nuevopass = hash.md5(pass);
            mod.setUsername(jtf_usuario.getText());
            mod.setPass(nuevopass);
            mod.setTipo((String) jcb_tipo.getSelectedItem());
            mod.setRfc(jtf_rfc.getText());
            
            if(modsql.registrar(mod)){
                JOptionPane.showMessageDialog(null, "Registro almacenado");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al almacenar");
            }
            } else
            {
                JOptionPane.showMessageDialog(null, "El usuario ya existe!");
            }
        }
        else
        {
          JOptionPane.showMessageDialog(null, "La contraseña no coincide");
        }
        
    }//GEN-LAST:event_jb_guardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JLabel jl_confirm_pass;
    private javax.swing.JLabel jl_pass;
    private javax.swing.JLabel jl_rfc;
    private javax.swing.JLabel jl_tipo;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JPanel jp_nuevo_user;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JPasswordField jp_pass_con;
    private javax.swing.JTextField jtf_rfc;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
