/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Escritorio;

/**
 *
 * @author manl_
 */
public class Registro_compras extends javax.swing.JFrame {

    /**
     * Creates new form Registro_compras
     */
    public Registro_compras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Tipo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jp_registro = new javax.swing.JPanel();
        jl_NO_PROVE = new javax.swing.JLabel();
        jl_nom_prov = new javax.swing.JLabel();
        jl_Comprobante = new javax.swing.JLabel();
        jl_cod_e = new javax.swing.JLabel();
        jl_Forma_pago = new javax.swing.JLabel();
        jl_Forma_entrega = new javax.swing.JLabel();
        jcb_Forma_pago = new javax.swing.JComboBox<>();
        jcb_Forma_entrega = new javax.swing.JComboBox<>();
        jtf_NO_PROVE = new javax.swing.JTextField();
        jrb_proveedor = new javax.swing.JRadioButton();
        jrb_herramienta = new javax.swing.JRadioButton();
        jrb_material = new javax.swing.JRadioButton();
        jl_tipo_articulo = new javax.swing.JLabel();
        jl_nombre_proveedor = new javax.swing.JLabel();
        jtf_codigo_articulo = new javax.swing.JTextField();
        jtf_Comprobante = new javax.swing.JTextField();
        jl_nombre_articulo = new javax.swing.JLabel();
        jl_dia = new javax.swing.JLabel();
        jl_mes = new javax.swing.JLabel();
        jl_año = new javax.swing.JLabel();
        jtf_dia = new javax.swing.JTextField();
        jtf_mes = new javax.swing.JTextField();
        jtf_año = new javax.swing.JTextField();
        jl_fecha = new javax.swing.JLabel();
        jl_costo = new javax.swing.JLabel();
        jtf_costo = new javax.swing.JTextField();
        jtf_cantidad = new javax.swing.JTextField();
        jl_cantidad = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_registro = new javax.swing.JTable();
        jp_botones = new javax.swing.JPanel();
        jb_Nuevo_prov = new javax.swing.JButton();
        jb_Nuevo_art = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_NO_PROVE.setText("No. Proveedor:");

        jl_nom_prov.setText("Nombre Proveedor:");

        jl_Comprobante.setText("Comprobante:");

        jl_cod_e.setText("Código articulo:");

        jl_Forma_pago.setText("Forma de pago:");

        jl_Forma_entrega.setText("Forma de entrega:");

        jcb_Forma_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "CREDITO", "DEBITO", "OTRO" }));

        jcb_Forma_entrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Correo", "Pendiente" }));

        jtf_NO_PROVE.setText("  ");

        jrb_proveedor.setSelected(true);
        jrb_proveedor.setText("Proveedor");

        bg_Tipo.add(jrb_herramienta);
        jrb_herramienta.setText("Herramienta");

        bg_Tipo.add(jrb_material);
        jrb_material.setText("Material");

        jl_tipo_articulo.setText("Tipo");

        jtf_codigo_articulo.setText(" ");

        jtf_Comprobante.setText("  ");

        jl_nombre_articulo.setText(" ");

        jl_dia.setText("Día");

        jl_mes.setText("Mes");

        jl_año.setText("Año");

        jtf_dia.setText("   ");

        jtf_mes.setText("    ");

        jtf_año.setText("2018");

        jl_fecha.setText("Fecha:");

        jl_costo.setText("Costo: $");

        jtf_costo.setText("00.00");

        jtf_cantidad.setText("1");

        jl_cantidad.setText("Cantidad:");

        jb_guardar.setText("Guardar");

        jb_cancelar.setText("Cancelar");

        javax.swing.GroupLayout jp_registroLayout = new javax.swing.GroupLayout(jp_registro);
        jp_registro.setLayout(jp_registroLayout);
        jp_registroLayout.setHorizontalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_registroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_Forma_entrega)
                    .addComponent(jl_Forma_pago)
                    .addComponent(jl_cod_e)
                    .addComponent(jl_Comprobante)
                    .addComponent(jl_nom_prov)
                    .addComponent(jl_NO_PROVE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_registroLayout.createSequentialGroup()
                        .addComponent(jtf_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addComponent(jl_dia)
                                .addGap(18, 18, 18)
                                .addComponent(jl_mes))
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_registroLayout.createSequentialGroup()
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jl_nombre_proveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addComponent(jtf_NO_PROVE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb_proveedor)))
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jl_tipo_articulo))
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jl_año)
                                        .addGroup(jp_registroLayout.createSequentialGroup()
                                            .addComponent(jrb_herramienta)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jrb_material)))
                                    .addComponent(jl_nombre_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_registroLayout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jb_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jb_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jp_registroLayout.createSequentialGroup()
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addComponent(jcb_Forma_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_cantidad))
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addComponent(jcb_Forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jl_costo))
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addComponent(jtf_codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(jl_fecha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_costo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jtf_cantidad))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jp_registroLayout.setVerticalGroup(
            jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_registroLayout.createSequentialGroup()
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_registroLayout.createSequentialGroup()
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_NO_PROVE)
                                    .addComponent(jtf_NO_PROVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrb_proveedor))
                                .addGap(18, 18, 18)
                                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_nom_prov)
                                    .addComponent(jl_nombre_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_nombre_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jp_registroLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jl_tipo_articulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_material)
                                    .addComponent(jrb_herramienta))))
                        .addGap(18, 18, 18)
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Comprobante)
                            .addComponent(jtf_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_registroLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_año)
                            .addComponent(jl_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_mes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cod_e)
                    .addComponent(jtf_codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fecha)
                    .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Forma_pago)
                    .addComponent(jcb_Forma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_costo)
                    .addComponent(jtf_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_Forma_entrega)
                        .addComponent(jcb_Forma_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_cantidad)
                        .addComponent(jtf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_cancelar)))
                .addContainerGap())
        );

        jt_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Comprobante", "Proveedor", "Articulo", "Cantidad", "Medida", "Tipo", "Fecha", "Forma de pago", "Costo", "Forma de entrega"
            }
        ));
        jScrollPane2.setViewportView(jt_registro);

        jb_Nuevo_prov.setText("Nuevo Proveedor");

        jb_Nuevo_art.setText("Nuevo Artículo");

        jb_modificar.setText("Modificar");

        jb_eliminar.setText("Eliminar");

        jb_salir.setText("Salir");

        javax.swing.GroupLayout jp_botonesLayout = new javax.swing.GroupLayout(jp_botones);
        jp_botones.setLayout(jp_botonesLayout);
        jp_botonesLayout.setHorizontalGroup(
            jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botonesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_botonesLayout.createSequentialGroup()
                        .addComponent(jb_Nuevo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(jp_botonesLayout.createSequentialGroup()
                        .addComponent(jb_Nuevo_prov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jp_botonesLayout.setVerticalGroup(
            jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificar)
                    .addComponent(jb_Nuevo_art))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_eliminar)
                    .addComponent(jb_Nuevo_prov)
                    .addComponent(jb_salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2))
                    .addComponent(jp_botones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Tipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_Nuevo_art;
    private javax.swing.JButton jb_Nuevo_prov;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<String> jcb_Forma_entrega;
    private javax.swing.JComboBox<String> jcb_Forma_pago;
    private javax.swing.JLabel jl_Comprobante;
    private javax.swing.JLabel jl_Forma_entrega;
    private javax.swing.JLabel jl_Forma_pago;
    private javax.swing.JLabel jl_NO_PROVE;
    private javax.swing.JLabel jl_año;
    private javax.swing.JLabel jl_cantidad;
    private javax.swing.JLabel jl_cod_e;
    private javax.swing.JLabel jl_costo;
    private javax.swing.JLabel jl_dia;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_mes;
    private javax.swing.JLabel jl_nom_prov;
    private javax.swing.JLabel jl_nombre_articulo;
    private javax.swing.JLabel jl_nombre_proveedor;
    private javax.swing.JLabel jl_tipo_articulo;
    private javax.swing.JPanel jp_botones;
    private javax.swing.JPanel jp_registro;
    private javax.swing.JRadioButton jrb_herramienta;
    private javax.swing.JRadioButton jrb_material;
    private javax.swing.JRadioButton jrb_proveedor;
    private javax.swing.JTable jt_registro;
    private javax.swing.JTextField jtf_Comprobante;
    private javax.swing.JTextField jtf_NO_PROVE;
    private javax.swing.JTextField jtf_año;
    private javax.swing.JTextField jtf_cantidad;
    private javax.swing.JTextField jtf_codigo_articulo;
    private javax.swing.JTextField jtf_costo;
    private javax.swing.JTextField jtf_dia;
    private javax.swing.JTextField jtf_mes;
    // End of variables declaration//GEN-END:variables
}
